# Generated by Django 6.0.1 on 2026-02-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupuser',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='signupuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='signupuser',
            name='last_name',
        ),
    ]
